version: "3"
services:
    api:
        build: .
        env_file:
            - .env
        ports:
            - 80:8000
        depends_on:
            - postgres
    
    postgres:
        image: postgres
        env_file:
            - db.env
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
